server:
  port: 9090  
spring:
  h2:
    console:
      enabled:true          
zuul:
  routes:
      gradle-demo:
        path: /hello/**, /java8core/**
        serviceId: gradle-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
